name: CI

env:
  go-version: "1.21"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
  push:
    branches: [develop]

jobs:
  quicktests:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}
      - name: fmt, tidy
        run: |
          make install
          make test-fmt
          make test-tidy
      - name: staticcheck
        run: make staticcheck

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}
      - name: lint
        run: |
          make install
          make lint-github-action

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install udev
        run: sudo apt-get install -y libudev-dev
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}
      - name: build
        run: make build

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}
      - name: go test
        run: make test
